In [114]:
import os
import pandas as pd

In [13]:
f'{1:02}'

'01'

In [109]:
root = "../data/subway/"
df = pd.DataFrame()

for month in range(1, 13):
    _df = pd.read_csv(root + f"Subway_2016{month:02}.csv", encoding='cp949')
    df = pd.concat([df, _df])

df

,날짜,호선,역명,구 분,할인,04 ~ 05,05 ~ 06,06 ~ 07,07 ~ 08,08 ~ 09,...,16~17시,17~18시,18~19시,19~20시,20~21시,21~22시,22~23시,23~24시,00~01시,01~02시
0,2016-01-01,1호선,서울역(150),승차,일반,44.0,298.0,243.0,490.0,909.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2016-01-01,1호선,서울역(150),승차,초등생,1.0,4.0,0.0,4.0,18.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2016-01-01,1호선,서울역(150),승차,청소년,8.0,33.0,15.0,16.0,54.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2016-01-01,1호선,서울역(150),승차,대학생,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2016-01-01,1호선,서울역(150),승차,우대,11.0,70.0,78.0,65.0,151.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7373,2016-12-29,NaN,남태령(434),NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,46.0,57.0,67.0,78.0,36.0,50.0,39.0,24.0,17.0,0.0
7374,2016-12-30,NaN,남태령(434),NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,93.0,162.0,275.0,164.0,41.0,29.0,22.0,10.0,1.0,0.0
7375,2016-12-30,NaN,남태령(434),NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,47.0,66.0,81.0,59.0,47.0,30.0,34.0,25.0,14.0,0.0
7376,2016-12-31,NaN,남태령(434),NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,142.0,246.0,307.0,36.0,15.0,24.0,10.0,9.0,0.0,0.0
7377,2016-12-31,NaN,남태령(434),NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,35.0,50.0,71.0,60.0,27.0,27.0,31.0,15.0,5.0,0.0

In [171]:
target = "../data/subway/"
total = []
for file in os.listdir(target):
    if file.split(".")[-1] == 'csv':
        total.append(pd.read_csv(f"{target}/{file}", encoding='euc-kr'))

total = [pd.read_csv(f"{target}/{file}", encoding='euc-kr') for file in os.listdir(target) if file.split(".")[-1] == 'csv']

In [172]:
for x in total:
    print(x.head(1))
    print(x.columns)
    print("===" * 50)

         역명          날짜  구분  05~06  06~07  07~08  08~09  09~10  10~11  11~12  \
0  서울역(150)  2016-10-01  승차    630    509   1068   2387   3272   3216   4369

   ...  16~17  17~18  18~19  19~20  20~21  21~22  22~23  23~24  00~01  01~02
0  ...   5175   4817   4402   3361   2715   3044   2928   1237     71      0

[1 rows x 24 columns]
Index(['역명', '날짜', '구분', '05~06', '06~07', '07~08', '08~09', '09~10', '10~11',
       '11~12', '12~13', '13~14', '14~15', '15~16', '16~17', '17~18', '18~19',
       '19~20', '20~21', '21~22', '22~23', '23~24', '00~01', '01~02'],
      dtype='str')
======================================================================================================================================================
           날짜   호선        역명 구 분  할인  04 ~ 05  05 ~ 06  06 ~ 07  07 ~ 08  \
0  2016-04-01  1호선  서울역(150)  승차  일반       23      301      418     1528

   08 ~ 09  ...  18 ~ 19  19 ~ 20  20 ~ 21  21 ~ 22  22 ~ 23  23 ~ 24  \
0     3079  ...     9957     5931     4086     4202     4104     2054

   00 ~ 01  01 ~ 02  02 ~ 03  03 ~ 04
0      283        0        0        0

[1 rows x 29 columns]
Index(['날짜', '호선', '역명', '구 분', '할인', '04 ~ 05', '05 ~ 06', '06 ~ 07',
       '07 ~ 08', '08 ~ 09', '09 ~ 10', '10 ~ 11', '11 ~ 12', '12 ~ 13',
       '13 ~ 14', '14 ~ 15', '15 ~ 16', '16 ~ 17', '17 ~ 18', '18 ~ 19',
       '19 ~ 20', '20 ~ 21', '21 ~ 22', '22 ~ 23', '23 ~ 24', '00 ~ 01',
       '01 ~ 02', '02 ~ 03', '03 ~ 04'],
      dtype='str')
======================================================================================================================================================
           날짜   호선        역명 구 분  할인  04 ~ 05  05 ~ 06  06 ~ 07  07 ~ 08  \
0  2016-05-01  1호선  서울역(150)  승차  일반       22      224      218      438

   08 ~ 09  ...  18 ~ 19  19 ~ 20  20 ~ 21  21 ~ 22  22 ~ 23  23 ~ 24  \
0     1002  ...     3497     3168     2508     3352     3426     1374

   00 ~ 01  01 ~ 02  02 ~ 03  03 ~ 04
0       39        0        0        0

[1 rows x 29 columns]
Index(['날짜', '호선', '역명', '구 분', '할인', '04 ~ 05', '05 ~ 06', '06 ~ 07',
       '07 ~ 08', '08 ~ 09', '09 ~ 10', '10 ~ 11', '11 ~ 12', '12 ~ 13',
       '13 ~ 14', '14 ~ 15', '15 ~ 16', '16 ~ 17', '17 ~ 18', '18 ~ 19',
       '19 ~ 20', '20 ~ 21', '21 ~ 22', '22 ~ 23', '23 ~ 24', '00 ~ 01',
       '01 ~ 02', '02 ~ 03', '03 ~ 04'],
      dtype='str')
======================================================================================================================================================
         역명          날짜  구분  05~06  06~07  07~08  08~09  09~10  10~11  11~12  \
0  서울역(150)  2016-11-01  승차    476    578   1846   3602   2562   2281   2846

   ...  16~17  17~18  18~19  19~20  20~21  21~22  22~23  23~24  00~01  01~02
0  ...   3844   4968   9447   5290   3746   3686   2216   1256    172      1

[1 rows x 24 columns]
Index(['역명', '날짜', '구분', '05~06', '06~07', '07~08', '08~09', '09~10', '10~11',
       '11~12', '12~13', '13~14', '14~15', '15~16', '16~17', '17~18', '18~19',
       '19~20', '20~21', '21~22', '22~23', '23~24', '00~01', '01~02'],
      dtype='str')
======================================================================================================================================================
         역명          날짜  구분  05~06  06~07  07~08  08~09  09~10  10~11  11~12  \
0  서울역(150)  2016-07-01  승차    436    553   1736   3165   2335   2364   2955

   ...  16~17  17~18  18~19  19~20  20~21  21~22  22~23  23~24  00~01  01~02
0  ...   4917   5715  11425   6182   4219   5023   4367   2381    334      0

[1 rows x 24 columns]
Index(['역명', '날짜', '구분', '05~06', '06~07', '07~08', '08~09', '09~10', '10~11',
       '11~12', '12~13', '13~14', '14~15', '15~16', '16~17', '17~18', '18~19',
       '19~20', '20~21', '21~22', '22~23', '23~24', '00~01', '01~02'],
      dtype='str')
======================================================================================================================================================
         역명          날짜  구분  05~06시  06~07시  07~08시  08~09시  09~10시  10~11시  \
0  서울역(150)  2016-12-01  승차     411     552    1792    3429    2737    2430

   11~12시  ...  16~17시  17~18시  18~19시  19~20시  20~21시  21~22시  22~23시  \
0    3161  ...    4145    4984    9595    5217    3492    3978    2742

   23~24시  00~01시  01~02시
0    1380     198       0

[1 rows x 24 columns]
Index(['역명', '날짜', '구분', '05~06시', '06~07시', '07~08시', '08~09시', '09~10시',
       '10~11시', '11~12시', '12~13시', '13~14시', '14~15시', '15~16시', '16~17시',
       '17~18시', '18~19시', '19~20시', '20~21시', '21~22시', '22~23시', '23~24시',
       '00~01시', '01~02시'],
      dtype='str')
======================================================================================================================================================
         역명          날짜  구분  05~06  06~07  07~08  08~09  09~10  10~11  11~12  \
0  서울역(150)  2016-06-01  승차    521    538   2111   3391   2454   2385   2821

   ...  16~17  17~18  18~19  19~20  20~21  21~22  22~23  23~24  00~01  01~02
0  ...   3764   5060   9536   5169   3393   3820   2440   1355    202      0

[1 rows x 24 columns]
Index(['역명', '날짜', '구분', '05~06', '06~07', '07~08', '08~09', '09~10', '10~11',
       '11~12', '12~13', '13~14', '14~15', '15~16', '16~17', '17~18', '18~19',
       '19~20', '20~21', '21~22', '22~23', '23~24', '00~01', '01~02'],
      dtype='str')
======================================================================================================================================================
           날짜   호선        역명 구 분  할인  04 ~ 05  05 ~ 06  06 ~ 07  07 ~ 08  \
0  2016-02-01  1호선  서울역(150)  승차  일반       34      322      459     2271

   08 ~ 09  ...  18 ~ 19  19 ~ 20  20 ~ 21  21 ~ 22  22 ~ 23  23 ~ 24  \
0     3267  ...     7705     5010     3448     3386     2145     1093

   00 ~ 01  01 ~ 02  02 ~ 03  03 ~ 04
0      141        0        0        0

[1 rows x 29 columns]
Index(['날짜', '호선', '역명', '구 분', '할인', '04 ~ 05', '05 ~ 06', '06 ~ 07',
       '07 ~ 08', '08 ~ 09', '09 ~ 10', '10 ~ 11', '11 ~ 12', '12 ~ 13',
       '13 ~ 14', '14 ~ 15', '15 ~ 16', '16 ~ 17', '17 ~ 18', '18 ~ 19',
       '19 ~ 20', '20 ~ 21', '21 ~ 22', '22 ~ 23', '23 ~ 24', '00 ~ 01',
       '01 ~ 02', '02 ~ 03', '03 ~ 04'],
      dtype='str')
======================================================================================================================================================
           날짜   호선        역명 구 분  할인  04 ~ 05  05 ~ 06  06 ~ 07  07 ~ 08  \
0  2016-03-01  1호선  서울역(150)  승차  일반       23      263      255      372

   08 ~ 09  ...  18 ~ 19  19 ~ 20  20 ~ 21  21 ~ 22  22 ~ 23  23 ~ 24  \
0      816  ...     3232     2505     2190     2538     1992      859

   00 ~ 01  01 ~ 02  02 ~ 03  03 ~ 04
0       56        0        0        0

[1 rows x 29 columns]
Index(['날짜', '호선', '역명', '구 분', '할인', '04 ~ 05', '05 ~ 06', '06 ~ 07',
       '07 ~ 08', '08 ~ 09', '09 ~ 10', '10 ~ 11', '11 ~ 12', '12 ~ 13',
       '13 ~ 14', '14 ~ 15', '15 ~ 16', '16 ~ 17', '17 ~ 18', '18 ~ 19',
       '19 ~ 20', '20 ~ 21', '21 ~ 22', '22 ~ 23', '23 ~ 24', '00 ~ 01',
       '01 ~ 02', '02 ~ 03', '03 ~ 04'],
      dtype='str')
======================================================================================================================================================
           날짜   호선        역명 구 분  할인  04 ~ 05  05 ~ 06  06 ~ 07  07 ~ 08  \
0  2016-01-01  1호선  서울역(150)  승차  일반       44      298      243      490

   08 ~ 09  ...  18 ~ 19  19 ~ 20  20 ~ 21  21 ~ 22  22 ~ 23  23 ~ 24  \
0      909  ...     2520     2129     1924     2038     1766      868

   00 ~ 01  01 ~ 02  02 ~ 03  03 ~ 04
0       52        0        0        0

[1 rows x 29 columns]
Index(['날짜', '호선', '역명', '구 분', '할인', '04 ~ 05', '05 ~ 06', '06 ~ 07',
       '07 ~ 08', '08 ~ 09', '09 ~ 10', '10 ~ 11', '11 ~ 12', '12 ~ 13',
       '13 ~ 14', '14 ~ 15', '15 ~ 16', '16 ~ 17', '17 ~ 18', '18 ~ 19',
       '19 ~ 20', '20 ~ 21', '21 ~ 22', '22 ~ 23', '23 ~ 24', '00 ~ 01',
       '01 ~ 02', '02 ~ 03', '03 ~ 04'],
      dtype='str')
======================================================================================================================================================
         역명          날짜  구분  05~06  06~07  07~08  08~09  09~10  10~11  11~12  \
0  서울역(150)  2016-08-01  승차    570    531   2293   3637   2826   2791   3584

   ...  16~17  17~18  18~19  19~20  20~21  21~22  22~23  23~24  00~01  01~02
0  ...   4173   4958   8676   5508   3364   3843   2475   1326    208      0

[1 rows x 24 columns]
Index(['역명', '날짜', '구분', '05~06', '06~07', '07~08', '08~09', '09~10', '10~11',
       '11~12', '12~13', '13~14', '14~15', '15~16', '16~17', '17~18', '18~19',
       '19~20', '20~21', '21~22', '22~23', '23~24', '00~01', '01~02'],
      dtype='str')
======================================================================================================================================================
         역명          날짜  구분  05~06  06~07  07~08  08~09  09~10  10~11  11~12  \
0  서울역(150)  2016-09-01  승차    451    570   1960   3740   2746   2579   2932

   ...  16~17  17~18  18~19  19~20  20~21  21~22  22~23  23~24  00~01  01~02
0  ...   3854   5127   9840   5359   3650   3897   2653   1517    266      1

[1 rows x 24 columns]
Index(['역명', '날짜', '구분', '05~06', '06~07', '07~08', '08~09', '09~10', '10~11',
       '11~12', '12~13', '13~14', '14~15', '15~16', '16~17', '17~18', '18~19',
       '19~20', '20~21', '21~22', '22~23', '23~24', '00~01', '01~02'],
      dtype='str')
======================================================================================================================================================

In [173]:
total = [pd.read_csv(f"{target}/{file}", encoding='euc-kr') for file in sorted(os.listdir(target)) if file.split(".")[-1] == 'csv']

In [177]:
total

[               날짜   호선        역명 구 분   할인  04 ~ 05  05 ~ 06  06 ~ 07  07 ~ 08  \
 0      2016-01-01  1호선  서울역(150)  승차   일반       44      298      243      490
 1      2016-01-01  1호선  서울역(150)  승차  초등생        1        4        0        4
 2      2016-01-01  1호선  서울역(150)  승차  청소년        8       33       15       16
 3      2016-01-01  1호선  서울역(150)  승차  대학생        0        0        0        0
 4      2016-01-01  1호선  서울역(150)  승차   우대       11       70       78       65
 ...           ...  ...       ...  ..  ...      ...      ...      ...      ...
 52665  2016-01-31  4호선  남태령(434)  승차   우대        0        5        7        4
 52666  2016-01-31  4호선  남태령(434)  하차   일반        0        0        4        9
 52667  2016-01-31  4호선  남태령(434)  하차  초등생        0        0        0        0
 52668  2016-01-31  4호선  남태령(434)  하차  청소년        0        0        0        0
 52669  2016-01-31  4호선  남태령(434)  하차   우대        0        0        7        7

        08 ~ 09  ...  18 ~ 19  19 ~ 20  20 ~ 21  21 ~ 22  22 ~ 23  23 ~ 24  \
 0          909  ...     2520     2129     1924     2038     1766      868
 1           18  ...       70       38       37       45       32        6
 2           54  ...      139      106      111      128       89       44
 3            0  ...        0        0        0        0        0        0
 4          151  ...      284      219      168      138      138       50
 ...        ...  ...      ...      ...      ...      ...      ...      ...
 52665        7  ...        8        5        6        0        2        1
 52666       14  ...       40       41       13       22       12       16
 52667        0  ...        0        2        0        0        0        0
 52668        0  ...        1        2        1        2        2        1
 52669        9  ...       20       12        2        4        5        3

        00 ~ 01  01 ~ 02  02 ~ 03  03 ~ 04
 0           52        0        0        0
 1            0        0        0        0
 2            1        0        0        0
 3            0        0        0        0
 4            4        0        0        0
 ...        ...      ...      ...      ...
 52665        0        0        0        0
 52666        2        0        0        0
 52667        0        0        0        0
 52668        0        0        0        0
 52669        2        0        0        0

 [52670 rows x 29 columns],
                날짜   호선        역명 구 분   할인  04 ~ 05  05 ~ 06  06 ~ 07  07 ~ 08  \
 0      2016-02-01  1호선  서울역(150)  승차   일반       34      322      459     2271
 1      2016-02-01  1호선  서울역(150)  승차  초등생        0        1        2        7
 2      2016-02-01  1호선  서울역(150)  승차  청소년        0       19       26       62
 3      2016-02-01  1호선  서울역(150)  승차  대학생        0        0        0        0
 4      2016-02-01  1호선  서울역(150)  승차   우대       15      108       89      187
 ...           ...  ...       ...  ..  ...      ...      ...      ...      ...
 50045  2016-02-29  4호선  남태령(434)  승차   우대        0        6       10       10
 50046  2016-02-29  4호선  남태령(434)  하차   일반        0        0       58       77
 50047  2016-02-29  4호선  남태령(434)  하차  초등생        0        0        0        0
 50048  2016-02-29  4호선  남태령(434)  하차  청소년        0        0        0        2
 50049  2016-02-29  4호선  남태령(434)  하차   우대        0        0       13       12

        08 ~ 09  ...  18 ~ 19  19 ~ 20  20 ~ 21  21 ~ 22  22 ~ 23  23 ~ 24  \
 0         3267  ...     7705     5010     3448     3386     2145     1093
 1           17  ...       18       10       19        7       12        6
 2           77  ...      136       96       71       77       89       43
 3            0  ...        0        0        0        0        0        0
 4          320  ...      529      289      234      181      100       45
 ...        ...  ...      ...      ...      ...      ...      ...      ...
 50045       14  ...       11        2        6        3        1        2
 50046      113  ...       34       49       29       31       35       18
 50047        1  ...        2        0        2        0        0        0
 50048        4  ...        3        1        1        0        2        1
 50049        6  ...       19       14        9       13        4       12

        00 ~ 01  01 ~ 02  02 ~ 03  03 ~ 04
 0          141        0        0        0
 1            0        0        0        0
 2            8        0        0        0
 3            0        0        0        0
 4            5        0        0        0
 ...        ...      ...      ...      ...
 50045        0        0        0        0
 50046        9        1        0        0
 50047        0        0        0        0
 50048        0        0        0        0
 50049        0        0        0        0

 [50050 rows x 29 columns],
                날짜   호선        역명 구 분   할인  04 ~ 05  05 ~ 06  06 ~ 07  07 ~ 08  \
 0      2016-03-01  1호선  서울역(150)  승차   일반       23      263      255      372
 1      2016-03-01  1호선  서울역(150)  승차  초등생        0        2        2        2
 2      2016-03-01  1호선  서울역(150)  승차  청소년        2       12       10       15
 3      2016-03-01  1호선  서울역(150)  승차  대학생        0        0        0        0
 4      2016-03-01  1호선  서울역(150)  승차   우대       13       82       67       86
 ...           ...  ...       ...  ..  ...      ...      ...      ...      ...
 53805  2016-03-31  4호선  남태령(434)  승차   우대        0        6        8        8
 53806  2016-03-31  4호선  남태령(434)  하차   일반        0        1       69       98
 53807  2016-03-31  4호선  남태령(434)  하차  초등생        0        0        0       14
 53808  2016-03-31  4호선  남태령(434)  하차  청소년        0        0        1      170
 53809  2016-03-31  4호선  남태령(434)  하차   우대        0        1       12        6

        08 ~ 09  ...  18 ~ 19  19 ~ 20  20 ~ 21  21 ~ 22  22 ~ 23  23 ~ 24  \
 0          816  ...     3232     2505     2190     2538     1992      859
 1            6  ...       52       33       21       37       19        7
 2           61  ...      188      162      118      130       77       49
 3            0  ...        0        0        0        0        0        0
 4          154  ...      386      267      209      168      111       42
 ...        ...  ...      ...      ...      ...      ...      ...      ...
 53805       17  ...       15        9        3        3        1        0
 53806      160  ...       46       56       24       22       44       13
 53807        0  ...        1        0        0        0        0        0
 53808       44  ...        2        3        1        1        2        0
 53809        8  ...       22       17       12       13        5        2

        00 ~ 01  01 ~ 02  02 ~ 03  03 ~ 04
 0           56        0        0        0
 1            0        0        0        0
 2            1        0        0        0
 3            0        0        0        0
 4            2        0        0        0
 ...        ...      ...      ...      ...
 53805        0        0        0        0
 53806       12        0        0        0
 53807        0        0        0        0
 53808        1        0        0        0
 53809        1        0        0        0

 [53810 rows x 29 columns],
                날짜   호선        역명 구 분   할인  04 ~ 05  05 ~ 06  06 ~ 07  07 ~ 08  \
 0      2016-04-01  1호선  서울역(150)  승차   일반       23      301      418     1528
 1      2016-04-01  1호선  서울역(150)  승차  초등생        0        0        2       14
 2      2016-04-01  1호선  서울역(150)  승차  청소년        1        9       25      105
 3      2016-04-01  1호선  서울역(150)  승차  대학생        0        0        0        0
 4      2016-04-01  1호선  서울역(150)  승차   우대        8      118      121      172
 ...           ...  ...       ...  ..  ...      ...      ...      ...      ...
 51913  2016-04-30  4호선  남태령(434)  승차   우대        1       11        4        7
 51914  2016-04-30  4호선  남태령(434)  하차   일반        0        0       27       24
 51915  2016-04-30  4호선  남태령(434)  하차  초등생        0        0        0        0
 51916  2016-04-30  4호선  남태령(434)  하차  청소년        0        0        0        0
 51917  2016-04-30  4호선  남태령(434)  하차   우대        0        1       12       11

        08 ~ 09  ...  18 ~ 19  19 ~ 20  20 ~ 21  21 ~ 22  22 ~ 23  23 ~ 24  \
 0         3079  ...     9957     5931     4086     4202     4104     2054
 1           17  ...       43       31       25       30       18       14
 2          171  ...      220      169      112      135      149       98
 3            0  ...        0        0        0        0        0        0
 4          328  ...      618      421      266      246      234       84
 ...        ...  ...      ...      ...      ...      ...      ...      ...
 51913       15  ...       21       11        5        4        2        1
 51914       35  ...       52       44       29       19       31       18
 51915        0  ...        0        0        0        0        2        0
 51916        1  ...        2        6        1        0        1        0
 51917       13  ...       12       16       11        6       10        2

        00 ~ 01  01 ~ 02  02 ~ 03  03 ~ 04
 0          283        0        0        0
 1            7        0        0        0
 2            4        0        0        0
 3            0        0        0        0
 4           16        0        0        0
 ...        ...      ...      ...      ...
 51913        0        0        0        0
 51914        4        0        0        0
 51915        0        0        0        0
 51916        1        0        0        0
 51917        2        0        0        0

 [51918 rows x 29 columns],
                날짜   호선        역명 구 분     할인  04 ~ 05  05 ~ 06  06 ~ 07  \
 0      2016-05-01  1호선  서울역(150)  승차     일반       22      224      218
 1      2016-05-01  1호선  서울역(150)  승차    초등생        0        1        1
 2      2016-05-01  1호선  서울역(150)  승차    청소년        3       10        8
 3      2016-05-01  1호선  서울역(150)  승차     우대       17       81      103
 4      2016-05-01  1호선  서울역(150)  승차  영어 일반        0        1        0
 ...           ...  ...       ...  ..    ...      ...      ...      ...
 52981  2016-05-31  4호선  남태령(434)  승차     우대        0        9       11
 52982  2016-05-31  4호선  남태령(434)  하차     일반        0        0       78
 52983  2016-05-31  4호선  남태령(434)  하차    초등생        0        0        0
 52984  2016-05-31  4호선  남태령(434)  하차    청소년        0        0        1
 52985  2016-05-31  4호선  남태령(434)  하차     우대        0        1       13

        07 ~ 08  08 ~ 09  ...  18 ~ 19  19 ~ 20  20 ~ 21  21 ~ 22  22 ~ 23  \
 0          438     1002  ...     3497     3168     2508     3352     3426
 1            4       11  ...       61       35       25       28       17
 2           14       59  ...      160      144      106      155      153
 3          110      192  ...      376      312      262      244      215
 4            1        3  ...       18       24       16       16       15
 ...        ...      ...  ...      ...      ...      ...      ...      ...
 52981       10       24  ...       21        5        6        4        0
 52982      106      165  ...       43       41       31       35       21
 52983       14        0  ...        0        0        0        0        0
 52984      149       42  ...        2        4        1        0        3
 52985       21       11  ...       22       14        9       11        5

        23 ~ 24  00 ~ 01  01 ~ 02  02 ~ 03  03 ~ 04
 0         1374       39        0        0        0
 1            1        0        0        0        0
 2           66        0        0        0        0
 3           73        2        0        0        0
 4            5        0        0        0        0
 ...        ...      ...      ...      ...      ...
 52981        0        0        0        0        0
 52982       18       11        0        0        0
 52983        0        0        0        0        0
 52984        1        0        0        0        0
 52985        2        2        0        0        0

 [52986 rows x 29 columns],
             역명          날짜  구분  05~06  06~07  07~08  08~09  09~10  10~11  \
 0     서울역(150)  2016-06-01  승차    521    538   2111   3391   2454   2385
 1     서울역(150)  2016-06-01  하차    355   1884   5611  11273   4688   2964
 2     서울역(150)  2016-06-02  승차    535    548   1946   3446   2636   2481
 3     서울역(150)  2016-06-02  하차    350   1823   5278  11206   4891   3102
 4     서울역(150)  2016-06-03  승차    480    529   1879   3418   2620   2469
 ...        ...         ...  ..    ...    ...    ...    ...    ...    ...
 7135  남태령(434)  2016-06-28  하차      4     79    304    211     67     30
 7136  남태령(434)  2016-06-29  승차     18     29     89    121    104     66
 7137  남태령(434)  2016-06-29  하차      0     84    278    177     83     43
 7138  남태령(434)  2016-06-30  승차     18     34    104    106     88     68
 7139  남태령(434)  2016-06-30  하차      1     66    271    204     75     37

       11~12  ...  16~17  17~18  18~19  19~20  20~21  21~22  22~23  23~24  \
 0      2821  ...   3764   5060   9536   5169   3393   3820   2440   1355
 1      2520  ...   2605   2725   3361   2380   1674   1631   1579    844
 2      2926  ...   3739   5172   9529   5559   3629   4001   2721   1503
 3      2460  ...   2682   3018   3453   2576   1864   1780   1694    874
 4      3064  ...   4897   6166  11148   6334   4094   4382   4607   2220
 ...     ...  ...    ...    ...    ...    ...    ...    ...    ...    ...
 7135     40  ...     48     56     64     69     32     49     41     20
 7136    107  ...     60    113    120     59     34     27     15      6
 7137     30  ...     56     54     67     45     43     36     31     26
 7138    157  ...     60    124    145     54     38     28     13      3
 7139     29  ...     60     57     47     60     37     47     35     25

       00~01  01~02
 0       202      0
 1       287     20
 2       244      0
 3       335     23
 4       372      0
 ...     ...    ...
 7135     12      2
 7136      1      0
 7137     15      1
 7138      2      0
 7139     13      1

 [7140 rows x 24 columns],
             역명          날짜  구분  05~06  06~07  07~08  08~09  09~10  10~11  \
 0     서울역(150)  2016-07-01  승차    436    553   1736   3165   2335   2364
 1     서울역(150)  2016-07-01  하차    307   1700   5147   9649   5225   3117
 2     서울역(150)  2016-07-02  승차    471    430    804   1948   2791   2680
 3     서울역(150)  2016-07-02  하차    237   1363   1942   2371   3237   3216
 4     서울역(150)  2016-07-03  승차    370    303    554   1197   1698   2103
 ...        ...         ...  ..    ...    ...    ...    ...    ...    ...
 7373  남태령(434)  2016-07-29  하차      1     64    103    163     52     60
 7374  남태령(434)  2016-07-30  승차     19     18     19    118     66     87
 7375  남태령(434)  2016-07-30  하차      3     53     42     46     44     56
 7376  남태령(434)  2016-07-31  승차      8     18     20     59     72     55
 7377  남태령(434)  2016-07-31  하차      2     16     22     25     36     33

       11~12  ...  16~17  17~18  18~19  19~20  20~21  21~22  22~23  23~24  \
 0      2955  ...   4917   5715  11425   6182   4219   5023   4367   2381
 1      2790  ...   3636   3350   4770   3703   2390   2166   1818    960
 2      3939  ...   4370   4261   4094   3125   2596   2727   2778   1193
 3      2826  ...   3386   3329   3069   2345   1999   1981   1740    886
 4      2731  ...   4066   3432   3713   3238   2749   3171   3268   1193
 ...     ...  ...    ...    ...    ...    ...    ...    ...    ...    ...
 7373     35  ...     46     53     65     71     52     58     43     14
 7374     55  ...    115     96     47     29     32      2     27      5
 7375     49  ...     32     66     40     53     37     31     30     26
 7376     54  ...     78     38     25     19     18     10     10      4
 7377     41  ...     50     43     44     61     30     32     32     22

       00~01  01~02
 0       334      0
 1       438     40
 2        42      0
 3       293      0
 4        40      0
 ...     ...    ...
 7373     12      1
 7374      0      0
 7375     13      0
 7376      0      0
 7377      3      0

 [7378 rows x 24 columns],
             역명          날짜  구분  05~06  06~07  07~08  08~09  09~10  10~11  \
 0     서울역(150)  2016-08-01  승차    570    531   2293   3637   2826   2791
 1     서울역(150)  2016-08-01  하차    428   2355   4963  10249   4398   3282
 2     서울역(150)  2016-08-02  승차    505    466   1608   3040   2518   2522
 3     서울역(150)  2016-08-02  하차    300   1779   4623   9591   4256   2945
 4     서울역(150)  2016-08-03  승차    526    508   1598   3127   2678   2541
 ...        ...         ...  ..    ...    ...    ...    ...    ...    ...
 7373  남태령(434)  2016-08-29  하차      4     83    257    209     44     34
 7374  남태령(434)  2016-08-30  승차     20     31    158    202    124     37
 7375  남태령(434)  2016-08-30  하차      3     80    262    227     49     34
 7376  남태령(434)  2016-08-31  승차     17     46    179    276    142     64
 7377  남태령(434)  2016-08-31  하차      2     55    226    243     67     30

       11~12  ...  16~17  17~18  18~19  19~20  20~21  21~22  22~23  23~24  \
 0      3584  ...   4173   4958   8676   5508   3364   3843   2475   1326
 1      3069  ...   3067   2912   3351   2494   1772   1457   1318    598
 2      3421  ...   4239   5128   9588   5230   3628   3909   2673   1494
 3      2782  ...   2959   2957   3588   2510   1773   1515   1261    661
 4      3202  ...   4055   5142   9337   4809   3437   3669   2652   1346
 ...     ...  ...    ...    ...    ...    ...    ...    ...    ...    ...
 7373     36  ...     58     63     77     67     46     35     37     14
 7374     45  ...    228    177    284    174     42     26      9      7
 7375     29  ...     52     58     53     58     58     35     40     21
 7376     64  ...     78    144    314    124     32     18     13      3
 7377     28  ...     46     53     55     66     40     38     32     25

       00~01  01~02
 0       208      0
 1       285     16
 2       210      0
 3       249     15
 4       200      0
 ...     ...    ...
 7373     12      1
 7374      2      0
 7375      6      0
 7376      1      0
 7377     11      0

 [7378 rows x 24 columns],
             역명          날짜  구분  05~06  06~07  07~08  08~09  09~10  10~11  \
 0     서울역(150)  2016-09-01  승차    451    570   1960   3740   2746   2579
 1     서울역(150)  2016-09-01  하차    338   1827   5151  11294   4938   3022
 2     서울역(150)  2016-09-02  승차    472    562   1788   3668   2792   2466
 3     서울역(150)  2016-09-02  하차    316   1696   4892  10603   4949   2942
 4     서울역(150)  2016-09-03  승차    547    488    955   2147   3055   3043
 ...        ...         ...  ..    ...    ...    ...    ...    ...    ...
 7135  남태령(434)  2016-09-28  하차      3     73    238    258     50     43
 7136  남태령(434)  2016-09-29  승차     15     26    186    212    154     57
 7137  남태령(434)  2016-09-29  하차      2     77    229    256     81     47
 7138  남태령(434)  2016-09-30  승차     13     30    215    194    121     75
 7139  남태령(434)  2016-09-30  하차      3     72    219    254     53     49

       11~12  ...  16~17  17~18  18~19  19~20  20~21  21~22  22~23  23~24  \
 0      2932  ...   3854   5127   9840   5359   3650   3897   2653   1517
 1      2544  ...   2804   3011   3663   2606   1976   1501   1591    781
 2      3073  ...   4639   6589  11266   6166   4213   4341   4425   2038
 3      2636  ...   3625   3738   5230   3715   2480   2035   1891   1063
 4      4064  ...   5069   4905   4319   3373   3168   3029   2833   1239
 ...     ...  ...    ...    ...    ...    ...    ...    ...    ...    ...
 7135     31  ...     45     70    103     47     45     46     27     28
 7136     48  ...    217    252    303    211     51     23     16      7
 7137     28  ...     54     53     65     59     29     33     44     24
 7138     49  ...    248    347    475    310    101     25     26      5
 7139     33  ...     51     58     84     95     36     41     48     31

       00~01  01~02

In [175]:
df1 = pd.concat(total[:5], ignore_index = True)

In [176]:
df1

,날짜,호선,역명,구 분,할인,04 ~ 05,05 ~ 06,06 ~ 07,07 ~ 08,08 ~ 09,...,18 ~ 19,19 ~ 20,20 ~ 21,21 ~ 22,22 ~ 23,23 ~ 24,00 ~ 01,01 ~ 02,02 ~ 03,03 ~ 04
0,2016-01-01,1호선,서울역(150),승차,일반,44,298,243,490,909,...,2520,2129,1924,2038,1766,868,52,0,0,0
1,2016-01-01,1호선,서울역(150),승차,초등생,1,4,0,4,18,...,70,38,37,45,32,6,0,0,0,0
2,2016-01-01,1호선,서울역(150),승차,청소년,8,33,15,16,54,...,139,106,111,128,89,44,1,0,0,0
3,2016-01-01,1호선,서울역(150),승차,대학생,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,2016-01-01,1호선,서울역(150),승차,우대,11,70,78,65,151,...,284,219,168,138,138,50,4,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261429,2016-05-31,4호선,남태령(434),승차,우대,0,9,11,10,24,...,21,5,6,4,0,0,0,0,0,0
261430,2016-05-31,4호선,남태령(434),하차,일반,0,0,78,106,165,...,43,41,31,35,21,18,11,0,0,0
261431,2016-05-31,4호선,남태령(434),하차,초등생,0,0,0,14,0,...,0,0,0,0,0,0,0,0,0,0
261432,2016-05-31,4호선,남태령(434),하차,청소년,0,0,1,149,42,...,2,4,1,0,3,1,0,0,0,0
261433,2016-05-31,4호선,남태령(434),하차,우대,0,1,13,21,11,...,22,14,9,11,5,2,2,0,0,0

In [117]:
df2 = pd.concat(total[5: -1], ignore_index=True)
df3 = total[-1].copy()

In [119]:
df1

,날짜,호선,역명,구 분,할인,04 ~ 05,05 ~ 06,06 ~ 07,07 ~ 08,08 ~ 09,...,18 ~ 19,19 ~ 20,20 ~ 21,21 ~ 22,22 ~ 23,23 ~ 24,00 ~ 01,01 ~ 02,02 ~ 03,03 ~ 04
0,2016-01-01,1호선,서울역(150),승차,일반,44,298,243,490,909,...,2520,2129,1924,2038,1766,868,52,0,0,0
1,2016-01-01,1호선,서울역(150),승차,초등생,1,4,0,4,18,...,70,38,37,45,32,6,0,0,0,0
2,2016-01-01,1호선,서울역(150),승차,청소년,8,33,15,16,54,...,139,106,111,128,89,44,1,0,0,0
3,2016-01-01,1호선,서울역(150),승차,대학생,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,2016-01-01,1호선,서울역(150),승차,우대,11,70,78,65,151,...,284,219,168,138,138,50,4,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261429,2016-05-31,4호선,남태령(434),승차,우대,0,9,11,10,24,...,21,5,6,4,0,0,0,0,0,0
261430,2016-05-31,4호선,남태령(434),하차,일반,0,0,78,106,165,...,43,41,31,35,21,18,11,0,0,0
261431,2016-05-31,4호선,남태령(434),하차,초등생,0,0,0,14,0,...,0,0,0,0,0,0,0,0,0,0
261432,2016-05-31,4호선,남태령(434),하차,청소년,0,0,1,149,42,...,2,4,1,0,3,1,0,0,0,0
261433,2016-05-31,4호선,남태령(434),하차,우대,0,1,13,21,11,...,22,14,9,11,5,2,2,0,0,0

In [118]:
df2

,역명,날짜,구분,05~06,06~07,07~08,08~09,09~10,10~11,11~12,...,16~17,17~18,18~19,19~20,20~21,21~22,22~23,23~24,00~01,01~02
0,서울역(150),2016-06-01,승차,521,538,2111,3391,2454,2385,2821,...,3764,5060,9536,5169,3393,3820,2440,1355,202,0
1,서울역(150),2016-06-01,하차,355,1884,5611,11273,4688,2964,2520,...,2605,2725,3361,2380,1674,1631,1579,844,287,20
2,서울역(150),2016-06-02,승차,535,548,1946,3446,2636,2481,2926,...,3739,5172,9529,5559,3629,4001,2721,1503,244,0
3,서울역(150),2016-06-02,하차,350,1823,5278,11206,4891,3102,2460,...,2682,3018,3453,2576,1864,1780,1694,874,335,23
4,서울역(150),2016-06-03,승차,480,529,1879,3418,2620,2469,3064,...,4897,6166,11148,6334,4094,4382,4607,2220,372,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43549,남태령(434),2016-11-28,하차,0,54,202,240,55,42,37,...,46,56,78,62,43,31,47,19,9,0
43550,남태령(434),2016-11-29,승차,20,32,173,204,141,76,67,...,150,231,365,106,39,38,8,4,1,0
43551,남태령(434),2016-11-29,하차,2,47,202,235,81,59,43,...,46,57,73,73,44,47,28,8,12,1
43552,남태령(434),2016-11-30,승차,24,31,178,212,129,70,59,...,69,157,347,74,36,65,12,6,1,0
43553,남태령(434),2016-11-30,하차,1,56,179,255,61,56,37,...,45,69,103,78,38,55,40,21,8,0

In [120]:
df3

,역명,날짜,구분,05~06시,06~07시,07~08시,08~09시,09~10시,10~11시,11~12시,...,16~17시,17~18시,18~19시,19~20시,20~21시,21~22시,22~23시,23~24시,00~01시,01~02시
0,서울역(150),2016-12-01,승차,411,552,1792,3429,2737,2430,3161,...,4145,4984,9595,5217,3492,3978,2742,1380,198,0
1,서울역(150),2016-12-01,하차,280,1680,4629,10313,5586,2920,2673,...,2905,3084,3715,2723,1794,1657,1533,761,373,32
2,서울역(150),2016-12-02,승차,434,520,1695,3456,2848,2568,3398,...,5180,6141,10682,6169,4169,4479,4554,1794,443,0
3,서울역(150),2016-12-02,하차,255,1609,4504,10225,5322,3050,2435,...,3692,3545,5575,3389,2141,2076,1928,1074,547,64
4,서울역(150),2016-12-03,승차,543,467,982,2080,3000,3077,4340,...,8023,6418,6575,4904,4742,4683,4654,1697,228,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7373,남태령(434),2016-12-29,하차,2,26,189,238,68,64,30,...,46,57,67,78,36,50,39,24,17,0
7374,남태령(434),2016-12-30,승차,18,23,125,165,111,80,61,...,93,162,275,164,41,29,22,10,1,0
7375,남태령(434),2016-12-30,하차,4,39,75,154,61,30,20,...,47,66,81,59,47,30,34,25,14,0
7376,남태령(434),2016-12-31,승차,16,22,19,93,81,71,60,...,142,246,307,36,15,24,10,9,0,0
7377,남태령(434),2016-12-31,하차,0,17,23,40,26,55,57,...,35,50,71,60,27,27,31,15,5,0

In [130]:
df1_grp = df1.groupby(['날짜', '호선', '역명', '구 분'], as_index=False).sum().drop('할인', axis=1)

In [131]:
df1_grp

,날짜,호선,역명,구 분,04 ~ 05,05 ~ 06,06 ~ 07,07 ~ 08,08 ~ 09,09 ~ 10,...,18 ~ 19,19 ~ 20,20 ~ 21,21 ~ 22,22 ~ 23,23 ~ 24,00 ~ 01,01 ~ 02,02 ~ 03,03 ~ 04
0,2016-01-01,1호선,동대문(155),승차,6,147,168,170,293,479,...,625,614,475,414,291,138,6,0,0,0
1,2016-01-01,1호선,동대문(155),하차,0,31,164,146,164,354,...,869,827,660,614,471,348,122,0,0,0
2,2016-01-01,1호선,동묘앞(159),승차,5,37,65,66,110,161,...,404,198,139,136,81,52,2,0,0,0
3,2016-01-01,1호선,동묘앞(159),하차,0,19,75,88,147,199,...,231,165,149,146,176,144,106,0,0,0
4,2016-01-01,1호선,서울역(150),승차,64,405,339,584,1144,1723,...,3076,2519,2281,2398,2056,996,58,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36171,2016-05-31,4호선,한성대입구(419),하차,0,61,459,974,2123,1631,...,1622,1563,1086,936,927,601,345,1,0,0
36172,2016-05-31,4호선,혜화(420),승차,0,154,391,889,1155,1051,...,4995,2942,2887,4534,4239,1936,320,0,0,0
36173,2016-05-31,4호선,혜화(420),하차,0,103,879,2827,6303,4144,...,4047,3419,1185,954,854,529,268,0,0,0
36174,2016-05-31,4호선,회현(425),승차,0,112,150,280,453,526,...,5286,3283,2492,1650,983,596,72,0,0,0
36175,2016-05-31,4호선,회현(425),하차,0,45,1348,3217,7461,4707,...,924,559,346,354,335,221,59,8,0,0

In [132]:
df1_grp_drop = df1_grp.drop(['04 ~ 05', '01 ~ 02', '02 ~ 03', '03 ~ 04'], axis=1)

In [134]:
df1_grp_drop

,날짜,호선,역명,구 분,05 ~ 06,06 ~ 07,07 ~ 08,08 ~ 09,09 ~ 10,10 ~ 11,...,15 ~ 16,16 ~ 17,17 ~ 18,18 ~ 19,19 ~ 20,20 ~ 21,21 ~ 22,22 ~ 23,23 ~ 24,00 ~ 01
0,2016-01-01,1호선,동대문(155),승차,147,168,170,293,479,543,...,1006,1034,1065,625,614,475,414,291,138,6
1,2016-01-01,1호선,동대문(155),하차,31,164,146,164,354,487,...,1297,1167,1158,869,827,660,614,471,348,122
2,2016-01-01,1호선,동묘앞(159),승차,37,65,66,110,161,245,...,1035,1129,975,404,198,139,136,81,52,2
3,2016-01-01,1호선,동묘앞(159),하차,19,75,88,147,199,359,...,908,587,353,231,165,149,146,176,144,106
4,2016-01-01,1호선,서울역(150),승차,405,339,584,1144,1723,2087,...,3639,3554,3200,3076,2519,2281,2398,2056,996,58
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36171,2016-05-31,4호선,한성대입구(419),하차,61,459,974,2123,1631,907,...,871,954,1425,1622,1563,1086,936,927,601,345
36172,2016-05-31,4호선,혜화(420),승차,154,391,889,1155,1051,1389,...,2848,3122,3802,4995,2942,2887,4534,4239,1936,320
36173,2016-05-31,4호선,혜화(420),하차,103,879,2827,6303,4144,3065,...,1979,2176,2469,4047,3419,1185,954,854,529,268
36174,2016-05-31,4호선,회현(425),승차,112,150,280,453,526,830,...,3261,3291,4416,5286,3283,2492,1650,983,596,72
36175,2016-05-31,4호선,회현(425),하차,45,1348,3217,7461,4707,3765,...,2000,1520,1079,924,559,346,354,335,221,59

In [136]:
import re

p = re.compile('([가-힣0-9]+)\(')

<>:3: SyntaxWarning: invalid escape sequence '\('
<>:3: SyntaxWarning: invalid escape sequence '\('
/var/folders/2v/b65115v14cvgvjztf82wr9x80000gn/T/ipykernel_66203/4126015520.py:3: SyntaxWarning: invalid escape sequence '\('
  p = re.compile('([가-힣0-9]+)\(')

In [146]:
df1_grp_drop['지하철역명'] = df1_grp_drop.역명.apply(lambda x : p.findall(x)[0])

AttributeError: 'DataFrame' object has no attribute '역명'

In [141]:
df1_grp_drop = df1_grp_drop[['날짜', '호선', '구 분', '지하철역명', '05 ~ 06', '06 ~ 07', '07 ~ 08', '08 ~ 09',
       '09 ~ 10', '10 ~ 11', '11 ~ 12', '12 ~ 13', '13 ~ 14', '14 ~ 15',
       '15 ~ 16', '16 ~ 17', '17 ~ 18', '18 ~ 19', '19 ~ 20', '20 ~ 21',
       '21 ~ 22', '22 ~ 23', '23 ~ 24', '00 ~ 01']].copy()

In [142]:
df1_grp_final = df1_grp_drop.groupby(['날짜', '호선', '구 분', '지하철역명'], as_index=False).sum()

In [143]:
df1_grp_final

,날짜,호선,구 분,지하철역명,05 ~ 06,06 ~ 07,07 ~ 08,08 ~ 09,09 ~ 10,10 ~ 11,...,15 ~ 16,16 ~ 17,17 ~ 18,18 ~ 19,19 ~ 20,20 ~ 21,21 ~ 22,22 ~ 23,23 ~ 24,00 ~ 01
0,2016-01-01,1호선,승차,동대문,147,168,170,293,479,543,...,1006,1034,1065,625,614,475,414,291,138,6
1,2016-01-01,1호선,승차,동묘앞,37,65,66,110,161,245,...,1035,1129,975,404,198,139,136,81,52,2
2,2016-01-01,1호선,승차,서울역,405,339,584,1144,1723,2087,...,3639,3554,3200,3076,2519,2281,2398,2056,996,58
3,2016-01-01,1호선,승차,시청,98,127,110,191,298,582,...,1069,1339,1458,1499,1383,1284,1198,675,375,9
4,2016-01-01,1호선,승차,신설동,113,176,172,301,354,471,...,528,587,605,497,335,248,220,166,70,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36171,2016-05-31,4호선,하차,총신대입구,39,450,1148,2290,1534,1025,...,1366,1643,2135,3273,3070,1782,1557,1605,892,342
36172,2016-05-31,4호선,하차,충무로,148,900,2962,10982,5577,3359,...,1457,1500,1449,1877,1470,747,640,546,385,177
36173,2016-05-31,4호선,하차,한성대입구,61,459,974,2123,1631,907,...,871,954,1425,1622,1563,1086,936,927,601,345
36174,2016-05-31,4호선,하차,혜화,103,879,2827,6303,4144,3065,...,1979,2176,2469,4047,3419,1185,954,854,529,268
36175,2016-05-31,4호선,하차,회현,45,1348,3217,7461,4707,3765,...,2000,1520,1079,924,559,346,354,335,221,59

In [153]:
df1_grp_final.columns

Index(['날짜', '구분', '지하철역명', '05~06', '06~07', '07~08', '08~09', '09~10',
       '10~11', '11~12', '12~13', '13~14', '14~15', '15~16', '16~17', '17~18',
       '18~19', '19~20', '20~21', '21~22', '22~23', '23~24', '00~01'],
      dtype='str')

In [150]:
df1_grp_final.columns = ["".join(x.split()) for x in df1_grp_final.columns]

In [152]:
df1_grp_final.drop('호선', axis=1, inplace=True)

In [155]:
df2 = df2[['날짜', '구분', '역명', '05~06', '06~07', '07~08', '08~09', '09~10', '10~11',
       '11~12', '12~13', '13~14', '14~15', '15~16', '16~17', '17~18', '18~19',
       '19~20', '20~21', '21~22', '22~23', '23~24', '00~01', '01~02']].copy()

In [157]:
df2.rename(columns={"역명" : "지하철역명"}, inplace=True)

In [160]:
df2['지하철역명'] = df2.지하철역명.apply(lambda x : p.findall(x)[0])

In [161]:
df2_final = df2.groupby(['날짜', '구분', '지하철역명'], as_index=False).sum()

In [162]:
df2_final.drop("01~02", axis=1, inplace=True)

In [165]:
df3.columns = [x.replace('시', '') for x in df3.columns]

In [166]:
df3.columns

Index(['역명', '날짜', '구분', '05~06', '06~07', '07~08', '08~09', '09~10', '10~11',
       '11~12', '12~13', '13~14', '14~15', '15~16', '16~17', '17~18', '18~19',
       '19~20', '20~21', '21~22', '22~23', '23~24', '00~01', '01~02'],
      dtype='str')

In [167]:
df3 = df3[['날짜', '구분', '역명', '05~06', '06~07', '07~08', '08~09', '09~10', '10~11',
       '11~12', '12~13', '13~14', '14~15', '15~16', '16~17', '17~18', '18~19',
       '19~20', '20~21', '21~22', '22~23', '23~24', '00~01']].copy()

In [169]:
df3.rename(columns={'역명' : '지하철역명'}, inplace=True)

In [170]:
df3

,날짜,구분,지하철역명,05~06,06~07,07~08,08~09,09~10,10~11,11~12,...,15~16,16~17,17~18,18~19,19~20,20~21,21~22,22~23,23~24,00~01
0,2016-12-01,승차,서울역(150),411,552,1792,3429,2737,2430,3161,...,3822,4145,4984,9595,5217,3492,3978,2742,1380,198
1,2016-12-01,하차,서울역(150),280,1680,4629,10313,5586,2920,2673,...,2535,2905,3084,3715,2723,1794,1657,1533,761,373
2,2016-12-02,승차,서울역(150),434,520,1695,3456,2848,2568,3398,...,5175,5180,6141,10682,6169,4169,4479,4554,1794,443
3,2016-12-02,하차,서울역(150),255,1609,4504,10225,5322,3050,2435,...,3391,3692,3545,5575,3389,2141,2076,1928,1074,547
4,2016-12-03,승차,서울역(150),543,467,982,2080,3000,3077,4340,...,6565,8023,6418,6575,4904,4742,4683,4654,1697,228
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7373,2016-12-29,하차,남태령(434),2,26,189,238,68,64,30,...,49,46,57,67,78,36,50,39,24,17
7374,2016-12-30,승차,남태령(434),18,23,125,165,111,80,61,...,111,93,162,275,164,41,29,22,10,1
7375,2016-12-30,하차,남태령(434),4,39,75,154,61,30,20,...,55,47,66,81,59,47,30,34,25,14
7376,2016-12-31,승차,남태령(434),16,22,19,93,81,71,60,...,116,142,246,307,36,15,24,10,9,0
7377,2016-12-31,하차,남태령(434),0,17,23,40,26,55,57,...,35,35,50,71,60,27,27,31,15,5

In [178]:
df3_final = df3.groupby(['날짜', '구분', '지하철역명'], as_index=False).sum()

In [179]:
print(df3_final.shape)
print(df2_final.shape)
print(df1_grp_final.shape)

(7378, 23)
(40260, 23)
(36176, 23)

In [188]:
subway_2016 = pd.concat([df1_grp_final, df2_final, df3_final], ignore_index=True)

In [190]:
subway_2016

,날짜,구분,지하철역명,05~06,06~07,07~08,08~09,09~10,10~11,11~12,...,15~16,16~17,17~18,18~19,19~20,20~21,21~22,22~23,23~24,00~01
0,2016-01-01,승차,동대문,147,168,170,293,479,543,625,...,1006,1034,1065,625,614,475,414,291,138,6
1,2016-01-01,승차,동묘앞,37,65,66,110,161,245,344,...,1035,1129,975,404,198,139,136,81,52,2
2,2016-01-01,승차,서울역,405,339,584,1144,1723,2087,2983,...,3639,3554,3200,3076,2519,2281,2398,2056,996,58
3,2016-01-01,승차,시청,98,127,110,191,298,582,700,...,1069,1339,1458,1499,1383,1284,1198,675,375,9
4,2016-01-01,승차,신설동,113,176,172,301,354,471,593,...,528,587,605,497,335,248,220,166,70,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83809,2016-12-31,하차,합정(238),101,356,461,689,1074,1128,1382,...,2220,2460,2824,2799,2131,1907,1803,1829,1036,557
83810,2016-12-31,하차,혜화(420),71,347,387,902,1478,1819,2666,...,4239,3958,4602,3759,1951,1332,1137,955,834,277
83811,2016-12-31,하차,홍대입구(239),103,513,561,1440,2512,3370,5109,...,8714,9022,9534,9318,7969,7075,6480,6550,5264,2802
83812,2016-12-31,하차,홍제(314),25,252,239,492,540,515,697,...,1150,1349,1619,1727,1290,1207,1254,1554,977,320
83813,2016-12-31,하차,회현(425),26,427,698,1662,2479,2109,2951,...,2232,1928,1568,1162,816,525,370,398,264,125

In [192]:
subway_2016['총합'] = subway_2016.iloc[:, 3:].sum(axis=1)

In [198]:
subway_2016.to_csv('../data/subway.csv')

In [193]:
subway_2016.groupby('지하철역명')['총합'].sum().sort_values(ascending=False)

지하철역명
강남          66615573
잠실          54489615
홍대입구        52525072
서울역         50762766
사당          49940581
              ...
용두(250)       149170
남태령(434)       96068
신답(245)        89594
지축(309)        83205
도림천(247)       72176
Name: 총합, Length: 229, dtype: int64

In [196]:
tmp = subway_2016.groupby(['날짜', '지하철역명']).sum().drop('구분', axis=1).to_json()